dataSource:
    driverClassName: com.mysql.cj.jdbc.Driver
    dbCreate: update
    username: root
    password: '0102301023'

environments:
    development:
        dataSource:
            dbCreate: update
            url: "jdbc:mysql://localhost/cadastro?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"